---
name: odin

services:
  gui-client:
    image: odin/gui-client
    build: ./gui-client
    ports:
      - "8080:8080"
  gui-api-1:
    image: odin/gui-api
    build: ./gui-api
  gui-api-2:
    image: odin/gui-api
    build: ./gui-api
  gui-api-3:
    image: odin/gui-api
    build: ./gui-api
  gui-kv:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6301:6379"
  search-api-1:
    image: odin/search-api
    build: ./search-api
  search-api-2:
    image: odin/search-api
    build: ./search-api
  search-api-3:
    image: odin/search-api
    build: ./search-api
  search-kv:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6302:6379"