[project]
name = "gui-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "starlette>=1.6.0",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "httpx2>=2.13.0",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "ty>=0.0.75",
]

[tool.ruff]
line-length = 176
src = ["src", "test"]


[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
